### PR TITLE
Development Server Support

### PR DESCRIPTION
**Pull request by platinummonkey**
This PR adds a few features

1. Adds Development server support via `bzl run`
1. Adds @ryanrf-ac s archetypes support https://github.com/stackb/rules_hugo/commit/881a1bf46416ef9f507adc380f97305c5064acfa 
1. Makes the relative_path a little more accomodating see #25 https://github.com/stackb/rules_hugo/compare/master...DataDog:master#diff-2e74d1b13ce9b7645c011139fc5931fdR15-R16
1. Fixes the example site hugo theme
1. Includes generated file support @nitnelave https://github.com/stackb/rules_hugo/commit/56a29b8300954b4cd36cb1b5446c8d4d3d4ca779 #26

### CODE REVIEW

**Comment by pcj** [comment]
Thanks @platinummonkey I'll try this out!

**Comment by pcj** [comment]
Some good changes in this, but the development server appears to reload on changes to files in the output tree.  I don't see an easy way to propagate changes back to the source tree...  Was it intended?

An alternative approach would be to use `ibazel //site:site` in conjunction with a static files server.

**Comment by platinummonkey** [comment]
> Some good changes in this, but the development server appears to reload on changes to files in the output tree. I don't see an easy way to propagate changes back to the source tree... Was it intended?
> 
> An alternative approach would be to use `ibazel //site:site` in conjunction with a static files server.

That's the intent and the workflow I use `ibazel $target` :)

**Comment by pcj** [comment]
So then if I understand correctly, using the hugo server here is not to facilitate hot regeneration of outputs, but rather just as a 'hugo-aware' webserver that gets restarted every time ibazel recompiles?

**Comment by platinummonkey** [comment]
correct, I'll be looking at another iteration where I can hint to ibazel when the runfiles for the hugo generation change explicitly to orchestrate the hot reloading steps

**Comment by pcj** [comment]
OK, I'll have another look using ibazel.  Documentation for the PR should be updated to suggest this workflow.

**Comment by f110** [comment]
This PR is really useful for me. I appreciated your work!
When I built my site with your PR, I needed to make small changes.

https://github.com/f110/rules_hugo/commit/a263d59ee7b9a7b6ed2da0553814bb7ad153a3cc
This patch makes `relative_path` to return correctly path if `src` is top-level.
Without this path, for example, `content` will be copied to `ontent`.

**Comment by pcj** [comment]
Sounds like we should put a little more effort into getting this merged.  @platinummonkey what is your status on this?  Any other changes planned?  Do you want to apply @f110 patch?

**Comment by platinummonkey** [comment]
@f110 's patch is included now 👍

**Comment by platinummonkey** [comment]
also getting new files added even with ibazel has this issue: https://github.com/bazelbuild/bazel-watcher/issues/135 so unfortunately this is about as far as we could take it without pushing this issue upstream for add/remove of files. It does detect runfile files that are modified.

**Comment by ryanrf-ac** [comment]
I don't use ibazel, so I'm not sure if this is out of line for this PR, but I've submitted [another PR](https://github.com/stackb/rules_hugo/pull/30) that allows the use of local theme files, instead of pulling from github, should anyone be interested in merging that with this PR (assuming it's in line with 'development server support').

My workflow is using hugo itself for local development, then having bazel build everything using the same files I've used for local development. This does mean you need to check the theme files into the running bazel, but I think it makes it slightly more deterministic in the long run.

**Comment by platinummonkey** [comment]
> I don't use ibazel, so I'm not sure if this is out of line for this PR, but I've submitted [another PR](https://github.com/stackb/rules_hugo/pull/30) that allows the use of local theme files, instead of pulling from github, should anyone be interested in merging that with this PR (assuming it's in line with 'development server support').
> 
> My workflow is using hugo itself for local development, then having bazel build everything using the same files I've used for local development. This does mean you need to check the theme files into the running bazel, but I think it makes it slightly more deterministic in the long run.

happy to include it :) will update this PR by end-of-day

**Comment by platinummonkey** [comment]
@ryanrf-ac included now 👍

**Comment by pcj** [comment]
LGTM, thanks @platinummonkey, @f110, @ryanrf-ac.

**Pull request merged**
